name: Build and Deploy to Cloud Run

on:
  push:
    branches:
    # - master
    - none

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  GCP_SA_KEY: ${{ secrets.RUN_SA_KEY }}
  RUN_REGION: us-central1
  SERVICE_NAME: cloud-run-demo

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.RUN_PROJECT }}
        service_account_key: ${{ secrets.RUN_SA_KEY }}
        export_default_credentials: true

    - name: Configure docker to use gcloud
      run: |-
        gcloud auth configure-docker

    - name: Build
      run: |-
        docker build -t "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" .

    - name: Publish
      run: |-
        docker push "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"

    - name: Deploy
      run: |-
        gcloud run deploy "$SERVICE_NAME" \
          --platform managed \
          --region "$RUN_REGION" \
          --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
          --project "$PROJECT_ID" \
          --port 80 \
          --allow-unauthenticated
